java_version=25
springboot_version=4.1.0
spring_dependency_management_version=1.1.7
micrometer_version=1.17.0
aspectjrt_version=1.9.25.1
junit_version=6.1.0
lombok_version=1.18.46
postgresql_version=42.7.11
h2_version=2.4.240
modelmapper_version=3.2.6
handlebars_version=4.5.2
opencsv_version=5.12.0
guava_version=33.6.0-jre
flyway_version=12.9.0