weatherserver:
  masterkey: 00000000-0000-0000-0000-000000000000

spring:
  datasource:
    url: jdbc:h2:file:./h2/db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

pull_weather:
  enabled: true
  url: https://weather.maxhenkel.de/api/v1/weather/current?id=1
  id: 1