server:
  error:
    path: /error
    whitelabel:
      enabled: false

management:
  server:
    port: 8070
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

spring:
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
  profiles:
    active: prod
  flyway:
    enabled: true
    group: true
    schemas: migrations
    locations: classpath:db/migration/weather
